title: Culinaire to Programmer
author: GregryD
email: gregorydionisio@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The story of how a chef made the switch. 
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  GregryD # DO NOT include the @ character, or else the build will fail!
theme: minima
show_excerpts: true # set to false to remove excerpts on the homepage
