title: From Recipe to Algorithum
author: Gregory Dionisio
email: gregorydionisio@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Documenting the migration from a culinarian to programmer. With only a small background in php lets see where this new world leads me. 

# social links
github_username:  GregryD # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

Theme: minima
